---
# ==============================================================================
# CLI Overridable Configuration (Use -e "var_name=value")
# ==============================================================================
is_gui_enabled: true
install_docker: true
target_user: gdario

# ==============================================================================
# System Defaults
# ==============================================================================
debian_mirror: "deb.debian.org"
debian_release: "testing"

# Package Categories
core_packages:
  - ripgrep
  - git
  - curl
  - unzip

programming_languages:
  rust: stable

user_packages:
  - bat
  - glow
  - jq
  - kubectl
  - kubectx
  - make
  - sqlite3
  - tree
  - tree-sitter-cli
  - zellij
