; ==============================================================================
; Ansible Inventory (hosts.ini)
; ==============================================================================

[workstations]
; Local workstation configuration
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

; Add other workstation/laptop hostnames here:
; laptop-01.personal.systems ansible_host=192.168.1.100

[cluster]
192.168.50.239 ansible_user=gdario

[bare_metal]
192.168.50.239 ansible_user=gdario


