[tasks."run:workstation"]
run = "ansible-playbook site.yml --tags workstation"
description = "Provision local workstation with Ansible"

[tasks."run:bare-metal-start"]
run = "ansible-playbook site.yml --tags bare-metal --ask-become-pass"
description = "Start the local PXE boot server to install Debian on bare-metal"

[tasks."run:bare-metal-stop"]
run = "ansible-playbook site.yml --tags bare-metal -e 'pxe_state=stopped' --ask-become-pass"
description = "Stop the local PXE boot server and clean up services"

[tasks."run:cluster"]
run = "ansible-playbook playbooks/provision_cluster.yml --ask-become-pass"
description = "Provision the cluster node (k3s, open-iscsi, and passive fancontrol)"

