---
- name: Bootstrap - Generate Inventory and Hosts
  hosts: localhost
  connection: local
  become: true
  vars:
    secrets_repo: "git@github.com:compilercomplied/hosts-secrets.git"
    temp_secrets_path: "/tmp/hosts-secrets-bootstrap"

  tasks:
    - name: Clone Secrets Repo to temp location
      become: no
      ansible.builtin.git:
        repo: "{{ secrets_repo }}"
        dest: "{{ temp_secrets_path }}"
        version: master
        accept_hostkey: yes
        force: yes

    - name: Read hosts map CSV
      ansible.builtin.slurp:
        src: "{{ temp_secrets_path }}/hosts/map.csv"
      register: hosts_csv_content

    - name: Parse CSV content
      set_fact:
        csv_lines: "{{ (hosts_csv_content['content'] | b64decode).split('\n') }}"

    - name: Debug CSV content
      debug:
        msg: "CSV Lines: {{ csv_lines }}"

    - name: Add servers to in-memory inventory
      ansible.builtin.add_host:
        name: "{{ item.split(',')[1] }}.personal.systems"
        groups: servers
        ansible_python_interpreter: /usr/bin/python3
        ansible_host: "{{ item.split(',')[2] }}"
      loop: "{{ csv_lines[1:] }}"
      when:
        - item | length > 0
        - not item.startswith('#')

    - name: Add workstations group (ensure localhost is in it)
      ansible.builtin.add_host:
        name: localhost
        groups: workstations
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3
      changed_when: false

    - name: Add all hosts to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item.split(',')[2] }} {{ item.split(',')[1] }}.personal.systems"
        regexp: "^{{ item.split(',')[2] }}\\s+{{ item.split(',')[1] }}\\.personal\\.systems"
        state: present
      loop: "{{ csv_lines[1:] }}"
      when:
        - item | length > 0
        - not item.startswith('#')

    - name: Remove temporary secrets repo
      ansible.builtin.file:
        path: "{{ temp_secrets_path }}"
        state: absent
- name: Provision All Systems
  hosts: all
  become: true
  roles:
    - common
    - users

- name: Provision Servers
  hosts: servers
  become: true
  roles:
    - docker

- name: Provision Laptop/Workstation
  hosts: workstations
  become: true
  roles:
    - programming
    - workstation
