---
- name: Load OS-specific toolchain variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/../roles/system/vars/{{ ansible_facts['os_family'] }}.yml"

- name: Include all toolchain definitions
  ansible.builtin.include_tasks: "{{ item }}"
  loop: "{{ query('fileglob', role_path + '/tasks/subtasks/*.yml') | sort }}"
