---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Run Platform Initialization
  ansible.builtin.include_tasks: "subtasks/setup_{{ ansible_facts['os_family'] }}.yml"

- name: Check if Platform Configuration exists
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/subtasks/configure_{{ ansible_facts['os_family'] }}.yml"
  register: platform_config_file

- name: Run Platform Configuration
  ansible.builtin.include_tasks: "subtasks/configure_{{ ansible_facts['os_family'] }}.yml"
  when: platform_config_file.stat.exists


