---
gui_taps:
  - nikitabobko/tap # Dependency for AeroSpace
  - felixkratz/formulae # Dependency for SketchyBar

gui_formulas:
  - sketchybar

gui_casks:
  - aerospace
  - alt-tab
  - betterdisplay
  - font-jetbrains-mono-nerd-font
  - lm-studio
  - obsidian
  - spotify
  - wezterm

mas_apps:
  - { id: 747648890, name: "Telegram" }
  - { id: 310633997, name: "WhatsApp" }
