---
gui_taps:
  - nikitabobko/tap # Dependency for AeroSpace
  - felixkratz/formulae # Dependency for SketchyBar

gui_formulas:
  - sketchybar

gui_casks:
  - alt-tab
  - ghostty
  - spotify
  - betterdisplay
  - obsidian
  - aerospace

mas_apps:
  - { id: 747648890, name: "Telegram" }
  - { id: 310633997, name: "WhatsApp" }
