---
# Debian/Linux Specific Variables
home_dir: "/home/{{ target_user }}"
shell_path: "/home/{{ target_user }}/.cargo/bin/nu"
nushell_config_dir: "{{ home_dir }}/.config/nushell"
starship_bin_path: "/usr/local/bin/starship"
bin_dir: "/usr/local/bin"
fnm_bin_path: "{{ home_dir }}/.fnm/fnm"

core_packages:
  - ripgrep
  - git
  - curl
  - build-essential
  - unzip
  - gnupg
  - neovim
  - vim
  - ssh
  - fnm
  - starship
  - libatomic1
  - wl-clipboard
  - zellij

gui_packages:
  - spotify-client
  - telegram-desktop
