---
- name: Load OS-specific user variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Ensure target user exists
  become: true
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: "{{ user_default_shell | default('/bin/bash') }}"
    groups: "{{ sudo_group | default('sudo') }}"
    append: yes
    create_home: "{{ create_user_home | default(true) | bool }}"
  # Only run user creation if not skipped
  when: not (skip_user_creation | default(false) | bool)
