---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Configure Linux-Specific Apt Sources
  ansible.builtin.include_tasks: "setup_{{ ansible_facts['os_family'] }}.yml"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Common Core Packages
  ansible.builtin.include_tasks: "packages_{{ ansible_facts['os_family'] }}.yml"

- name: Check if Git LFS is initialized
  become: "{{ user_become }}"
  become_user: "{{ target_user }}"
  ansible.builtin.command: git config --global filter.lfs.smudge
  register: git_lfs_check
  changed_when: false
  failed_when: false
  check_mode: no

- name: Initialize Git LFS
  become: "{{ user_become }}"
  become_user: "{{ target_user }}"
  ansible.builtin.command: git lfs install
  when: git_lfs_check.rc != 0

- name: Ensure .config directory exists
  become: "{{ ansible_facts['os_family'] == 'Debian' }}"
  ansible.builtin.file:
    path: "{{ home_dir }}/.config"
    state: directory
    owner: "{{ target_user if ansible_facts['os_family'] == 'Debian' else omit }}"
    group: "{{ target_user if ansible_facts['os_family'] == 'Debian' else omit }}"
    mode: '0755'

- name: Clone Secrets Repo
  become: "{{ user_become }}"
  become_user: "{{ target_user }}"
  ansible.builtin.git:
    repo: 'git@github.com:compilercomplied/secrets.git'
    dest: "{{ home_dir }}/secrets"
    version: master
    accept_hostkey: yes
    force: yes
  check_mode: no
