---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Configure Linux-Specific Apt Sources
  ansible.builtin.include_tasks: "setup_{{ ansible_facts['os_family'] }}.yml"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Common Core Packages
  ansible.builtin.include_tasks: "packages_{{ ansible_facts['os_family'] }}.yml"
