---
- name: Install Common Core Packages (Debian)
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages + (workstation_packages if is_workstation | default(false) | bool else []) }}"
    state: present

- name: Start Syncthing service (Debian)
  ansible.builtin.systemd:
    name: syncthing
    scope: user
    enabled: yes
    state: started
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_effective_user_id }}"
  when: is_workstation | default(false) | bool
