---
- name: Provision Workstations
  hosts: workstations
  become: false
  tags: workstation
  roles:
    - users
    - common
    - workstation
    - role: docker
      when: ansible_os_family == 'Debian'
