---
- name: Provision Servers
  hosts: servers
  become: true
  tags: servers
  roles:
    - common
    - role: users
      when: not (skip_user_creation | default(false) | bool)
    # - docker # TODO: Refactor this as the docker configuration was moved/split for workstation (Darwin/Debian)
    - cluster
